### ISSUE TITLE
 CRASH AFTER UPDATE  14.08.2019

### ISSUE THREAD

**Issue by stvnkng** [xardch/sensum#19]
any help plz

**Comment by stvnkng** [comment]
yes i found out when u diable optimation in vs it make sensum crashed ...

**Comment by martinjanas** [comment]
go into patterns.h
replace #define GAME_RULES_PROXY ... 

with this:

 #define GAME_RULES_PROXY		 xorstr_("client.dll"), xorstr_("A1 ? ? ? ? 8B 0D ? ? ? ? 6A 00 68 ? ? ? ? C6")

**Comment by stvnkng** [comment]
> A1 ? ? ? ? 8B 0D ? ? ? ? 6A 00 68 ? ? ? ? C6

hi, when  u spawn in map, csgo crashed

**Comment by stvnkng** [comment]
does csgo crashed if u disable optimation for you?

**Comment by martinjanas** [comment]
http://www.mediafire.com/file/vhhyxznj33cfdpv/Sensum_NO_JC_build_3.rar

here is fixed version, enjoy.
