### ISSUE TITLE
I added many more features to Sensum, download inside.

### ISSUE THREAD

**Issue by martinjanas** [xardch/sensum#20]
http://www.mediafire.com/file/k0gm5brwahsbmbz/Sensum_NO_JC_build_3.1_Hotfix.rar

feature list: https://pastebin.com/Ls7X17HG

**Comment by stvnkng** [comment]
> 
> 
> http://www.mediafire.com/file/vhhyxznj33cfdpv/Sensum_NO_JC_build_3.rar
> 
> feature list: https://pastebin.com/Ls7X17HG

hi appreciate your effort but your version is bugging u cant even play here my screen it looks like this when spawning into the game http://prntscr.com/otez56 , should i use  ' -nod3d9ex ' ??

**Comment by martinjanas** [comment]
use -disable_d3d9ex

**Comment by stvnkng** [comment]
still same

**Comment by martinjanas** [comment]
Make sure you dont use -nod3d9ex with -disable...

**Comment by stvnkng** [comment]
-disable_d3d9ex yes i put this in my launch otion but my screen is still bugging  http://prntscr.com/otez56

**Comment by martinjanas** [comment]
Paste your launch options.

**Comment by stvnkng** [comment]
-high -autoexec  -novid -thread 4 -refresh 75 -freq 75  -nojoy  -tickrate 128 -lv  +exec autoexec.cfg -disable_d3d9ex -insecure

**Comment by martinjanas** [comment]
Try to remove your refresh & freq options.

You can remove -lv,it doesnt work today.

**Comment by stvnkng** [comment]
no the cheat is broken, waiting for another person to confirm

**Comment by martinjanas** [comment]
I Think I found the fix,but i cant test that.You have to do that.

1. Go to hooks.cpp

2. Find painttraverse hook

replace this:

if (!strcmp(panelName, "FocusOverlayPanel"))

with this:
if (!strcmp(panelName, "MatSystemTopPanel"))

**Comment by stvnkng** [comment]
i have big fps issue with this cheat , i know what was wrong the  mouse cursor should not be hidden when pressing 'insert' to apeaer the menu cheat then u can go into a map

**Comment by martinjanas** [comment]
Did you replace it? Just look for: panelName, "Focus" using ctrl + f

**Comment by stvnkng** [comment]
i mean the version u uploaded without the fix in hooks.cpp is not fps optimised. http://prntscr.com/otg4of

**Comment by martinjanas** [comment]
My fps are fine, https://pastebin.com/jQzwVXDA

**Comment by martinjanas** [comment]
Thats really weird,unless you re-enabled "Draw boxes on grenades" then there's nothing that can cause fps drops.

How many fps you have without inject ?
How many fps you have if you kick all bots?

**Comment by smigielek** [comment]
Hello, I tried selfnade function and i think you made a mistake.
Shouldn't it be 	
if (grenade->m_flThrowStrength() >= 0.11f || grenade->m_flThrowStrength() <= 0.10f
		|| cmd->viewangles.yaw < 88.0f) 
		return;
 in place of
if (grenade->m_flThrowStrength() >= 0.11f || grenade->m_flThrowStrength() <= 0.10f
		|| cmd->viewangles.yaw > -88.0f) 
		return;

Otherwise it  only throws grenade if you look down

**Comment by Madzleii** [comment]
Its bigging screen same way as 

> I Think I found the fix,but i cant test that.You have to do that.
> 
> 1. Go to hooks.cpp
> 2. Find painttraverse hook
> 
> replace this:
> 
> if (!strcmp(panelName, "FocusOverlayPanel"))
> 
> with this:
> if (!strcmp(panelName, "MatSystemTopPanel"))

It didnt help me. Itill same result.

**Comment by smigielek** [comment]
If your screen is black and things are flashing like on the ss that someone sent you should try going into misc options and changing both fov options  i think this is because we are using old confing and it doesn't have fov saved on it and its setting it to 0.

**Comment by stvnkng** [comment]
> 
> 
> My fps are fine, https://pastebin.com/jQzwVXDA

u need to really play the game when u are close to bots or someone is moving u can feel the shuttering, last version u dont get it :)

**Comment by Madzleii** [comment]
> If your screen is black and things are flashing like on the ss that someone sent you should try going into misc options and changing both fov options i think this is because we are using old confing and it doesn't have fov saved on it and its setting it to 0.

Thank you, I didnt realize that.

**Comment by stvnkng** [comment]
is there a way to disable the colour sky ???

**Comment by stvnkng** [comment]
> 
> 
> > I Think I found the fix,but i cant test that.You have to do that.
> > 
> > 1. Go to hooks.cpp
> > 2. Find painttraverse hook
> > 
> > replace this:
> > if (!strcmp(panelName, "FocusOverlayPanel"))
> > with this:
> > if (!strcmp(panelName, "MatSystemTopPanel"))
> 
> It didnt help me. Still same result.

do u get fps shattering/drop with this new version sensum?

**Comment by martinjanas** [comment]
I tested the fps again.Screenshots inside.

https://pastebin.com/K5Tm5Cht

I will try to optimize the cheat as I can.

**Comment by 0x1Eren** [comment]
I got like 7967 warnings on visual studio lul. VS even crashed.

**Comment by martinjanas** [comment]
Build with tools v142 or switch to v141.Im using v142

**Comment by 0x1Eren** [comment]
and the cheat is broken AF. When i press Tab it doesn't go away. When i press Esc the main menu doesn't go away. I can't even join games because the screen freezes.

**Comment by smigielek** [comment]
@0x1Eren  you should try this

> If your screen is black and things are flashing like on the ss that someone sent you should try going into misc options and changing both fov options i think this is because we are using old confing and it doesn't have fov saved on it and its setting it to 0.

**Comment by smigielek** [comment]
I already had fps drops on random ocasions with olders sources I'm getting drops to 20 fps. 
I will actually check every function later today maybe we will find out what causes it



> > > I Think I found the fix,but i cant test that.You have to do that.
> > > 
> > > 1. Go to hooks.cpp
> > > 2. Find painttraverse hook
> > > 
> > > replace this:
> > > if (!strcmp(panelName, "FocusOverlayPanel"))
> > > with this:
> > > if (!strcmp(panelName, "MatSystemTopPanel"))
> > 
> > 
> > It didnt help me. Still same result.
> 
> do u get fps shattering/drop with this new version sensum?

**Comment by 0x1Eren** [comment]
> @0x1Eren you should try this
> 
> > If your screen is black and things are flashing like on the ss that someone sent you should try going into misc options and changing both fov options i think this is because we are using old confing and it doesn't have fov saved on it and its setting it to 0.

Which FOV options?

**Comment by martinjanas** [comment]
I hope I fixed the fov black screen stuff, from float back to INT. Edit your configs if you did previously.

**Comment by 0x1Eren** [comment]
> Build with tools v142 or switch to v141.Im using v142

Im still getting the errors.

**Comment by martinjanas** [comment]
> > Im still getting the errors.
> > Edit: Use Debug

Could you upload screenshot of errors?

**Comment by stvnkng** [comment]
> 
> 
> > > Im still getting the errors.
> > > Edit: Use Debug
> 
> Could you upload screenshot of errors?

hi when u compile the dll with ' whole program optimistion on' in VS u dont get lag fps isssue , but how to make it undetected with added junk code etc ,changing signature if u need to put optimistion on

**Comment by martinjanas** [comment]
> hi when u compile the dll with ' whole program optimistion on' in VS u dont get lag fps isssue , but  > how to make it undetected with added junk code etc ,changing signature if u need to put optimistion > on

Move this file into the cheat main folder,run it around 60 times and it will be junkcoded.8000+ lines is enough and its efficient. http://www.mediafire.com/file/nveuduymygttqgf/AutoJunk.exe

**Comment by stvnkng** [comment]
> 
> 
> > hi when u compile the dll with ' whole program optimistion on' in VS u dont get lag fps isssue , but  > how to make it undetected with added junk code etc ,changing signature if u need to put optimistion > on
> 
> Move this file into the cheat main folder,run it around 60 times and it will be junkcoded.8000+ lines is enough and its efficient. http://www.mediafire.com/file/nveuduymygttqgf/AutoJunk.exe

I mean if u cant compile it with optimisation off , junk code will be useless

**Comment by Madzleii** [comment]
> > > I Think I found the fix,but i cant test that.You have to do that.
> > > 
> > > 1. Go to hooks.cpp
> > > 2. Find painttraverse hook
> > > 
> > > replace this:
> > > if (!strcmp(panelName, "FocusOverlayPanel"))
> > > with this:
> > > if (!strcmp(panelName, "MatSystemTopPanel"))
> > 
> > 
> > It didnt help me. Still same result.
> 
> do u get fps shattering/drop with this new version sensum?

Yes i do. Normally i run csgo 200fps+ with sensum it goes down to 120+- and if i start discord it goes down to 60fps and less.

**Comment by 0x1Eren** [comment]
> > > Im still getting the errors.
> > > Edit: Use Debug
> 
> Could you upload screenshot of errors?

![Screenshot_19](https://user-images.githubusercontent.com/52881209/63209022-eb538180-c0db-11e9-98bd-c11771448197.png)

**Comment by martinjanas** [comment]
Those are just warnings man,you can safely ignore them.Just click on that 3947 warnings button and they wont show up.

**Comment by Madzleii** [comment]
I just find bug. Any fixes ? https://giphy.com/gifs/cmUMWZZ5FiwVLaRU3t/html5

**Comment by smigielek** [comment]
I think that the real model isn't removed.
I found out that fakelag isn't working.
Selfnade is crashing while in matchmaking.

**Comment by 0x1Eren** [comment]
> I just find bug. Any fixes ? https://giphy.com/gifs/cmUMWZZ5FiwVLaRU3t/html5
> It have something to do with aimbot https://giphy.com/gifs/hTCsxoApnH1DtckxUo/html5

Got the same problem. And how do i turn off fast duck?

**Comment by Madzleii** [comment]
> > I just find bug. Any fixes ? https://giphy.com/gifs/cmUMWZZ5FiwVLaRU3t/html5
> > It have something to do with aimbot https://giphy.com/gifs/hTCsxoApnH1DtckxUo/html5
> 
> Got the same problem. And how do i turn off fast duck?

There isnt option to turn it off

**Comment by Madzleii** [comment]
Backtrack chams and color of it doesnt save in config :/

**Comment by 0x1Eren** [comment]
@martinjanas 


> Backtrack chams and color of it doesnt save in config :/

**Comment by martinjanas** [comment]
Fast duck is bind-able.If you want to disable it you need to click again on the bind button and then click somewhere in the menu to unbind it.

Yes,Im aware of all bugs,Im planning to fix/rewrite all I can.

**Comment by FrenchWave** [comment]
Some features are cool like the new RCS but damn this version have just so much bugs that you can't use it. I will stay on your second version that works perfectly fine. Hopefully u know how to fix all this.
