### ISSUE TITLE
ThirdPerson problem

### ISSUE THREAD

**Issue by Madzleii** [xardch/sensum#3]
When third person is on, you flash and blink (Offset problem i think) It happend for me on map Office

**Comment by xardch** [comment]
Do you use this on your own server? Blinking should never occur on online servers.

You can try this solution:
https://www.unknowncheats.me/forum/counterstrike-global-offensive/319202-rendering-attached-weapons-thirdperson.html

**Comment by Madzleii** [comment]
I think that it was just a bug. It isnt happening to me more.
